[package]
category = "Simulation"
authors = ["PhysX"]
title = "Physics Bundle"
description = "Omniverse physics bundle extension."
repository = ""
keywords = ["physics", "physx", "vehicle"]

version = "107.3.0-oss.0"

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Example"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.physx" = { version = "107.3.0-oss.0", exact = true }
"omni.physics.physx" = { version = "107.3.0-oss.0", exact = true }
"omni.physics.stageupdate" = { version = "107.3.0-oss.0", exact = true }
"omni.physx.ui" = { version = "107.3.0-oss.0", exact = true }
"omni.physx.vehicle" = { version = "107.3.0-oss.0", exact = true }
"omni.physx.demos" = { version = "107.3.0-oss.0", exact = true }
"omni.kit.property.physx" = { version = "107.3.0-oss.0", exact = true }
"omni.usdphysics" = { version = "107.3.0-oss.0", exact = true }
"omni.usdphysics.ui" = { version = "107.3.0-oss.0", exact = true }
"omni.physx.cct" = { version = "107.3.0-oss.0", exact = true }
"omni.physx.commands" = { version = "107.3.0-oss.0", exact = true }
"omni.physx.camera" = { version = "107.3.0-oss.0", exact = true }
"omni.physx.supportui" = { version = "107.3.0-oss.0", exact = true }
"omni.physx.graph" = { version = "107.3.0-oss.0", exact = true }
"omni.physx.telemetry" = { version = "107.3.0-oss.0", exact = true }
"omni.physx.asset_validator" = { version = "107.3.0-oss.0", exact = true }

[[test]]
args = [
    "--no-window",
    "--/exts/omni.kit.telemetry/skipDeferredStartup=true",
]
dependencies = [
]
pyCoverageThreshold = 0
waiver = "This is a bundle extension, it is not expected to have any coverage."
