[package]
title = "Physics Schema Plugin"
description="Handles loading of USD PhysicsSchema."
repository = ""
keywords = ["physics"]
category = "simulation"

version = "107.3.0-oss.0"
authors = ["PhysX"]

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Core"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.usd.libs" = { }
"omni.usd.schema.physx" = { version = "107.3.0-oss.0", exact = true }

[[python.module]]
name = "omni.usdphysics"

[[python.module]]
name = "omni.usdphysics.scripts"

[[native.plugin]]
path = "bin/*.plugin"

[[test]]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."
