[package]
title = "Physics Schema Tests"
description="Tests loading of PhysicsSchema."
repository = ""
keywords = ["physics", "tests"]
category = "simulation"

version = "107.3.0-oss.0"
authors = ["PhysX"]

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Internal"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.kit.stage_templates" = {}
"omni.usdphysics" = { version = "107.3.0-oss.0", exact = true }
"omni.physx.tests" = { version = "107.3.0-oss.0", exact = true }

[[python.module]]
name = "omni.usdphysicstests"

[[native.plugin]]
path = "bin/*.plugin"

[[test]]
dependencies = [
]
pyCoverageThreshold = 0
