[package]
title = "PhysX Core"
description="PhysX 5 integration code."

version = "107.3.0-oss.0"
authors = ["PhysX"]

repository = ""
keywords = ["physics", "physx"]
category = "simulation"

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Core"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.usd.libs" = {}
"omni.usd.schema.physx" = { version = "107.3.0-oss.0", exact = true }
"omni.usdphysics" = { version = "107.3.0-oss.0", exact = true }
"usdrt.scenegraph" = {}
"omni.gpucompute.plugins" = {}
"omni.physx.cooking" = { version = "107.3.0-oss.1", exact = true }
"omni.physx.foundation" = { version = "107.3.0-oss.1", exact = true }

[[python.module]]
name = "omni.physx"

[[python.module]]
name = "omni.physx.scripts"

[[native.plugin]]
path = "bin/omni.physx.plugin"

[[test]]
dependencies = [
   "omni.usd"
]
waiver = "PhysX tests are running in a separate CI pipeline. Tests are in separate extensions."
