[package]
category = "Internal"
authors = ["PhysX"]
title = "PhysX Visual Tests"
description="Physx visual tests"
repository=""
keywords = ["physx", "tests"]

version = "107.3.0-oss.0"

icon = "icons/icon.png"
preview_image = "icons/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Example"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.physx.tests" = { version = "107.3.0-oss.0", exact = true }
"omni.physx.ui" = { version = "107.3.0-oss.0", exact = true }
"omni.kit.property.physx" = { version = "107.3.0-oss.0", exact = true }
"omni.kit.ui_test" = {}
"omni.kit.viewport.utility" = {}

[[python.module]]
name = "omni.physxtestsvisual"

[[test]]
dependencies = [
    "omni.hydra.rtx",
    "omni.kit.mainwindow",
    "omni.physx.supportui",
    "omni.kit.window.stage",
]
args = [
    "--/physics/developmentMode=true",
    "--/rtx-transient/post/aa/limitedOps=false",
    "--/renderer/enabled=rtx",
    "--/renderer/active=rtx",
    "--/rtx/materialDb/syncLoads=true",
    "--/rtx/hydra/materialSyncLoads=true",
    "--/renderer/multiGpu/autoEnable=false",
    "--/renderer/multiGpu/enabled=false",
    "--/renderer/debug/validation/enabled=false",
    "--/omni.kit.plugin/syncUsdLoads=true",
    "--/app/asyncRendering=false",
    "--/app/window/width=1280",
    "--/app/window/height=1024",
    "--no-window",
    "--/app/font/file='${fonts}/OpenSans-SemiBold.ttf'",
    "--/app/font/size=16",
]
timeout = 2700
pyCoverageThreshold = 0
